### ISSUE TITLE
Accept wildcard paths 

### ISSUE THREAD

**Issue by ferrislucas** [ferrislucas/promptr#14]
It’s not super convenient having to specify each file to send separated by a space. It would be more ergonomic to be able to pass paths with wildcards. 

Example:
Something like this would pass all files that end in .rb or .js. The  ‘-r’ would make it recursive:
promptr *.rb *.js -r -p “summarize how this code works”

**Comment by kevingilbert100** [comment]
I like this - I'll try and toss a PR in for you!

**Comment by ferrislucas** [comment]
Thank you @kevingilbert100 please do!

**Comment by ferrislucas** [comment]
@kevingilbert100 I’m doing some refactoring here: https://github.com/ferrislucas/promptr/pull/23


I’ll probably merge that soon. If you end up opening a PR then I’m happy to resolve any merge conflicts. I really appreciate any contribution - even if it’s unfinished work. I think this would be a really good UX improvement.

**Comment by ferrislucas** [comment]
This is working. Closing
