### ISSUE TITLE
Error using GPT 4

### ISSUE THREAD

**Issue by mossy426** [ferrislucas/promptr#31]
I followed the command in the readme:

$ promptr -m gpt4 -p "Cleanup the code in these files" app/index.js

and get the below error:

```
data: {
      error: {
        message: 'The model: `gpt-4` does not exist',
        type: 'invalid_request_error',
        param: null,
        code: 'model_not_found'
      }
    }
```

**Comment by ferrislucas** [comment]
@mossy426 have you requested and received access to GPT4? There’s a wait list that you have to sit on before you get access to GPT4 unfortunately.

**Comment by ferrislucas** [comment]
I’m going to close this because I think you don’t have API access. Let me know if you’re seeing this error and you have access to the GPT4 API, and I’ll reopen and take a look. Thanks for reaching out!
