### ISSUE TITLE
Getting an error when trying to run gpt4

### ISSUE THREAD

**Issue by Industrial** [ferrislucas/promptr#33]
When running `promptr -m gpt4 -p "Clean up the code in this file" foo.js`

I get:

```
data: {
      error: {
        message: 'The model: `gpt-4` does not exist',
        type: 'invalid_request_error',
        param: null,
        code: 'model_not_found'
      }
    }
```

**Comment by Industrial** [comment]
I have access to the Pro plan

**Comment by ferrislucas** [comment]
Hi @Industrial , you have to sign up for gpt4 access separately here: https://openai.com/waitlist/gpt-4-api
