### ISSUE TITLE
"npm run bundle" packages.json fix for windows

### ISSUE THREAD

**Issue by richdrummer33** [ferrislucas/promptr#50]
[package_json (win).zip](https://github.com/ferrislucas/promptr/files/12504965/package_json.win.zip)

Attached zip contains a modified packages.json for windows (basically the cp command and path needed to be modified for win).

**Comment by ferrislucas** [comment]
Thanks for opening this issue @richdrummer33  Do you recall what problems you had that were fixed by your changes?

**Comment by ferrislucas** [comment]
@richdrummer33 would you mind making a pull request with your changes?

**Comment by richdrummer33** [comment]
Can do! Might later today.

**Comment by ferrislucas** [comment]
I didn't see a significant difference in the attached zip file. I'm probably missing something. I'm going to close this issue because it's so old, but please feel free to re-open if you get the energy to work on it. Thanks again for contributing the issue!
