### ISSUE TITLE
Allow to set the base_url for the openai gateway

### ISSUE THREAD

**Issue by shuther** [ferrislucas/promptr#60]
Add the ability to change the openai endpoint (baseURL) as per [OpenAI SDK ](https://github.com/openai/openai-node) to be able to leverage self hosted LLM.

**Comment by ferrislucas** [comment]
@shuther thanks for opening this issue. Sorry for the slow response. Do you have any interest in creating a PR for this functionality? I think it would be great to support local models and additional providers.

**Comment by ferrislucas** [comment]
@keiththomps did you have any luck with this? It looks like you added the ability to specify a base url, did that with for you? I really appreciate your contribution. 

https://github.com/ferrislucas/promptr/compare/main...keiththomps:promptr:main

**Comment by keiththomps** [comment]
Tested it using the Shopify proxy and it works 👍 https://github.com/ferrislucas/promptr/pull/64 Sorry for not adding a test.

**Comment by ferrislucas** [comment]
Thank you very much for the PR and your time @keiththomps !
