### ISSUE TITLE
Template paths have to be absolute 

### ISSUE THREAD

**Issue by ferrislucas** [ferrislucas/promptr#7]
It would be nice if relative paths worked. I’d like to be able to use ~/something/whatever.txt

**Comment by waldobeest** [comment]
Something to consider here is to package these templates into JSON available to the build step I have added in a build [MR](https://github.com/ferrislucas/promptr/pull/9). This way the templates dont have to accompany the binary

**Comment by ferrislucas** [comment]
@waldobeest I wonder if the templates should just be referred to using a url? So you could just say `promptr -t https://whatever.com/template.txt` to refer to a template via url. The built in templates (like "refactor" or "test-first" etc) could just map to url's internally. Then the templates don't need to be distributed. I'm thinking out loud. 

I'd love to hear more about how you're using this and how promptr could be more useful to you. 

I really appreciate your contributions!
